server:
  port: 10090

logging:
  level:
    root: INFO
    com.baloise.open: DEBUG
    org.apache.kafka.clients: WARN
    io.confluent.kafka.serializers: WARN

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  flyway:
    schemas: sports

edw:
  kafka:
    system-id: strava-connect
    schema-registry-url: "http://localhost:9012"
    activity:
      topic-name: "lz.edw.strava-connect.activity"
      value-serializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
      value-deserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
      specific-avro-reader: true

